apiVersion: v1
kind: Service
metadata:
  name: email-assistant-backend
spec:
  selector:
    app: email-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: email-assistant-frontend
spec:
  selector:
    app: email-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
